
<body style="background-image: url('images/cool-background.png');">
    <!-- Navigation -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header" align="center" style="font-family:forte;"><font color="#556B2F"> FEEDBACK ANALYZER </font> </h1>
                
            </div>
        </div>
        <!-- /.row -->

        <!-- Intro Content -->
        <div class="row" style="margin-bottom:50px;margin-left:50px;margin-right:50px">
           
               <P style="text-align: justify;font-size:160%;">
Teacher-student relations in any educational institute play a critical role in the 
development of the Student in particular and the institute in general. To determine the 
capabilities of students, students are being evaluated by the process of well-defined 
examination systems. At the same, for determining the capabilities of teachers, a 
feedback system is required to be kept in place. Feedback mechanism system ensures 
a detailed analysis of the performance of the teacher’s w.r.t the various parameters. 
The feedback system provides capabilities for selecting a particular course for 
feedback and then the reports are being generated by the admin. It provides a proper 
feedback to the concerned teachers and hence can result in good results as the 
concerned would then work on their weaker points as the same would be reflected 
from their individual feedback report. The existing manual system for the same would 
take a lot of time for analyzing the performance and the manual processes are 
susceptible to errors. The students are being given a proper login and the one who 
gives the feedback is not stored but only the feedback is being stored. This ensures a 
fair feedback to the concerned faculty involved. Every time a feedback is given, a 
counter is stored in the database which gives the information about the number of 
students who have given feedback and the same counter is used to determine the 
average performance analysis. The aim of the project is to reduce the time for getting 
feedback data and provide an in depth analysis about the performance. The system so
developed helps in making the decision processes and the selection processes much 
more effective.
</P> 
               
            </div>
        </div>
        <!-- /.row -->

        <!-- Footer -->
     </body>